<Project Sdk="Microsoft.NET.Sdk.Web">

  <!--
    فایل پروژه (csproj) - نسخه MVC
    مشخص‌کننده نوع پروژه و پکیج‌های مورد نیاز
    Microsoft.NET.Sdk.Web: این SDK مخصوص برنامه‌های وب ASP.NET Core است
    TargetFramework net8.0: نسخه دات‌نت ۸ به عنوان تارگت پروژه
  -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SportsStore</RootNamespace>
  </PropertyGroup>

  <!--
    پکیج‌های NuGet مورد نیاز پروژه:
    1) EntityFrameworkCore.SqlServer: پروایدر EF Core برای SQL Server
    2) EntityFrameworkCore.Design: ابزارهای طراحی برای Migrations
    3) EntityFrameworkCore.Tools: ابزارهای خط فرمان برای Scaffold و Migration
    4) Identity.EntityFrameworkCore: سیستم احراز هویت مبتنی بر EF Core
  -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.9" />
  </ItemGroup>

</Project>
