<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5d23c691-f940-4b91-8450-a17b3df50c05</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Platform.zip" />
    <None Remove="Platform_Commented.zip" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
