// =============================================================================
// فایل Migrations/20260601205447_initial.Designer.cs — فایل طراحی Migration
// =============================================================================
// ⚠️ این فایل به صورت خودکار (Auto-generated) توسط EF Core تولید شده است.
// هرگز این فایل را دستی ویرایش نکنید زیرا با هر بار اجرای Migration
// بازنویسی خواهد شد.
//
// کاربرد این فایل:
// - ذخیره "عکس فوری" (Snapshot) از مدل دیتابیس در زمان ایجاد Migration.
// - EF Core از این عکس فوری برای مقایسه با مدل فعلی و تشخیص تغییرات
//   در Migration های بعدی استفاده می‌کند.
// =============================================================================

// <auto-generated /> — این علامت نشان می‌دهد فایل به صورت خودکار تولید شده.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    // -----------------------------------------------------------------
    // [DbContext(typeof(DataContext))]: مشخص می‌کند این Migration مربوط به کدام DbContext است.
    // [Migration("20260601205447_initial")]: شناسه یکتای این Migration.
    //   این شناسه در جدول __EFMigrationsHistory در دیتابیس ذخیره می‌شود
    //   تا EF Core بداند کدام Migration ها اعمال شده‌اند.
    [DbContext(typeof(DataContext))]
    [Migration("20260601205447_initial")]
    partial class initial
    {
        /// <inheritdoc />
        // -----------------------------------------------------------------
        // BuildTargetModel — ساخت مدل دیتابیس
        // -----------------------------------------------------------------
        // این متد مدل کامل دیتابیس را در زمان این Migration تعریف می‌کند.
        // هر موجودیت (Entity)، خصوصیات، کلیدها، Index ها و روابط در اینجا مشخص شده‌اند.
        // EF Core از این مدل برای مقایسه با مدل فعلی برنامه استفاده می‌کند.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // -------------------------------------------------------------
            // Annotation های سطح مدل
            // -------------------------------------------------------------
            modelBuilder
                // ProductVersion: نسخه EF Core که این Migration با آن ایجاد شده.
                .HasAnnotation("ProductVersion", "9.0.2")
                // Relational:MaxIdentifierLength: حداکثر طول نام اشیاء دیتابیس.
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // UseIdentityColumns: فعال‌سازی Identity Columns برای SQL Server.
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // =============================================================
            // تعریف موجودیت Category
            // =============================================================
            modelBuilder.Entity("WebApp.Models.Category", b =>
                {
                    // CategoryId: کلید اصلی، bigint، Identity (خودکار افزایشی).
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd() // مقدار به صورت خودکار تولید می‌شود.
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    // Name: رشته الزامی، nvarchar(max).
                    b.Property<string>("Name")
                        .IsRequired() // NOT NULL در دیتابیس.
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId"); // تعریف کلید اصلی.

                    b.ToTable("Categories"); // نام جدول در دیتابیس.
                });

            // =============================================================
            // تعریف موجودیت Product
            // =============================================================
            modelBuilder.Entity("WebApp.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    // CategoryId: کلید خارجی به Categories (bigint).
                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    // Price: decimal(8, 2) — مطابق [Column(TypeName = "decimal(8, 2)")] در مدل.
                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    // SupplierId: کلید خارجی به Suppliers (bigint).
                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId");

                    // Index روی CategoryId — برای بهبود عملکرد JOIN و فیلتر.
                    b.HasIndex("CategoryId");

                    // Index روی SupplierId — برای بهبود عملکرد JOIN و فیلتر.
                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            // =============================================================
            // تعریف موجودیت Supplier
            // =============================================================
            modelBuilder.Entity("WebApp.Models.Supplier", b =>
                {
                    b.Property<long>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupplierId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            // =============================================================
            // تعریف روابط (Relationships)
            // =============================================================

            // رابطه Product → Category (چند به یک)
            modelBuilder.Entity("WebApp.Models.Product", b =>
                {
                    // HasOne: هر Product یک Category دارد.
                    // WithMany: هر Category چند Product دارد.
                    // HasForeignKey: ستون ارتباطی CategoryId در جدول Products.
                    // OnDelete(Cascade): حذف دسته‌بندی = حذف محصولات آن.
                    b.HasOne("WebApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired(); // Relationship الزامی است (Category نمی‌تواند null باشد).

                    // رابطه Product → Supplier (چند به یک)
                    b.HasOne("WebApp.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    // تعریف Navigation Properties
                    b.Navigation("Category");
                    b.Navigation("Supplier");
                });

            // تعریف Navigation Property برای Category (لیست Products)
            modelBuilder.Entity("WebApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            // تعریف Navigation Property برای Supplier (لیست Products)
            modelBuilder.Entity("WebApp.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}