// =============================================================================
// فایل Migrations/DataContextModelSnapshot.cs — عکس فوری (Snapshot) مدل فعلی
// =============================================================================
// ⚠️ این فایل به صورت خودکار (Auto-generated) توسط EF Core تولید شده است.
// هرگز این فایل را دستی ویرایش نکنید.
//
// تفاوت این فایل با فایل Designer:
// - Designer.cs: مدل را در زمان یک Migration خاص ذخیره می‌کند.
// - DataContextModelSnapshot.cs: مدل را در حالت فعلی (آخرین Migration) ذخیره می‌کند.
//
// وقتی شما یک Migration جدید ایجاد می‌کنید (dotnet ef migrations add ...)،
// EF Core این Snapshot را با مدل فعلی برنامه مقایسه می‌کند و تفاوت‌ها
// (جداول جدید، ستون‌های اضافه/حذف شده و...) را به عنوان Migration جدید ایجاد می‌کند.
// =============================================================================

// <auto-generated /> — این علامت نشان می‌دهد فایل به صورت خودکار تولید شده.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    // -----------------------------------------------------------------
    // [DbContext(typeof(DataContext))]: این Snapshot مربوط به DataContext است.
    // ModelSnapshot: کلاس پایه برای Snapshot های مدل.
    // -----------------------------------------------------------------
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        // -----------------------------------------------------------------
        // BuildModel — ساخت مدل کامل دیتابیس
        // -----------------------------------------------------------------
        // محتوای این متد دقیقاً مشابه BuildTargetModel در فایل Designer.cs
        // آخرین Migration است. هر بار که Migration جدیدی اضافه می‌شود،
        // این فایل به‌روزرسانی می‌شود تا مدل فعلی را منعکس کند.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // -------------------------------------------------------------
            // Annotation های سطح مدل (مشابه Designer.cs)
            // -------------------------------------------------------------
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // =============================================================
            // موجودیت Category — جدول Categories
            // =============================================================
            modelBuilder.Entity("WebApp.Models.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            // =============================================================
            // موجودیت Product — جدول Products
            // =============================================================
            // شامل خصوصیات، کلید اصلی و Index های روی کلیدهای خارجی.
            modelBuilder.Entity("WebApp.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            // =============================================================
            // موجودیت Supplier — جدول Suppliers
            // =============================================================
            modelBuilder.Entity("WebApp.Models.Supplier", b =>
                {
                    b.Property<long>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupplierId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            // =============================================================
            // روابط بین موجودیت‌ها
            // =============================================================
            // Product → Category: رابطه چند به یک با Cascade Delete.
            // Product → Supplier: رابطه چند به یک با Cascade Delete.
            modelBuilder.Entity("WebApp.Models.Product", b =>
                {
                    b.HasOne("WebApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            // Navigation Properties
            modelBuilder.Entity("WebApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApp.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}